### ISSUE TITLE
Using cosmiconfig

### ISSUE THREAD

**Issue by jacoobes** [sern-handler/cli#100]
https://github.com/cosmiconfig/cosmiconfig

Would this be a better way to have a configuration file for sern? 
This would reduce the need to import and parse a json file, and it allows flexibility in where users want to put sern.config.json

**Comment by jacoobes** [comment]
This module also allows caching for faster sern cli startup

**Comment by needhamgary** [comment]
Well as for being faster loading and catching, sounds great! But I don't think any location other than root project would be necessary for the config file
